# Generated by Django 5.0.1 on 2024-03-22 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='desciption',
            new_name='description',
        ),
    ]
